name: Tests

on:
  pull_request:
  push:
    branches: ["main"]

jobs:                                                                                                                   
  generate-matrix:
    name: 'Generate matrix from cabal'
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract the tested GHC versions
        id: set-matrix
        uses: kleidukos/get-tested@v0.1.9.1
        with:
          cabal-file: ghcup-gtk.cabal
          ubuntu-version: '26.04'
          version: 0.1.9.1

  tests:                                                                                                                
    name: ${{ matrix.ghc }} on ${{ matrix.os }}                                                                         
    needs: generate-matrix
    runs-on: ${{ matrix.os }}                                                                                           
    strategy:                                                                                                           
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v3
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - name: Set up Haskell
      id: setup-haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Configure environment
      run: |
        sudo apt update
        sudo apt install -y \
          libadwaita-1-dev \
          libcairo2-dev \
          libfreetype-dev \
          libgdk-pixbuf-2.0-dev \
          libgirepository1.0-dev \
          libglib2.0-dev \
          libgraphene-1.0-dev \
          libgtk-4-dev \
          libharfbuzz-dev \
          liblzma-dev \
          libpango1.0-dev \
          zlib1g-dev
        echo "$HOME/.ghcup/bin" >> $GITHUB_PATH
        echo "$HOME/.cabal/bin" >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        cabal freeze

    - name: Cache
      uses: actions/cache@v5
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-${{ hashFiles('**/plan.json') }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Build
      run: |
        make build

    - name: Test
      run: |
        cabal test
